[package]
name = "knx-usb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
libusb = "0.3.0"
#hid = "0.4" # { path = "../rust-hid" }
